package com.redhat.demo.nas;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPLICATION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "APPLICATION_ID_GENERATOR", sequenceName = "APPLICATION_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("申請人")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("需求容量(MB)")
   private java.lang.Integer quota;

   @org.kie.api.definition.type.Label("主機IP")
   private java.lang.String mountIp;

   @org.kie.api.definition.type.Label("掛載點")
   private java.lang.String mountPoint;

   @org.kie.api.definition.type.Label("存儲IP")
   private java.lang.String storageIp;

   @org.kie.api.definition.type.Label("狀態(結果)")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "\u5E33\u865F")
   private java.lang.String username;

   @org.kie.api.definition.type.Label(value = "\u5BC6\u78BC")
   private java.lang.String password;

   public Application()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getQuota()
   {
      return this.quota;
   }

   public void setQuota(java.lang.Integer quota)
   {
      this.quota = quota;
   }

   public java.lang.String getMountIp()
   {
      return this.mountIp;
   }

   public void setMountIp(java.lang.String mountIp)
   {
      this.mountIp = mountIp;
   }

   public java.lang.String getMountPoint()
   {
      return this.mountPoint;
   }

   public void setMountPoint(java.lang.String mountPoint)
   {
      this.mountPoint = mountPoint;
   }

   public java.lang.String getStorageIp()
   {
      return this.storageIp;
   }

   public void setStorageIp(java.lang.String storageIp)
   {
      this.storageIp = storageIp;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public Application(java.lang.Long id, java.lang.String name,
         java.lang.Integer quota, java.lang.String mountIp,
         java.lang.String mountPoint, java.lang.String storageIp,
         java.lang.String status, java.lang.String username,
         java.lang.String password)
   {
      this.id = id;
      this.name = name;
      this.quota = quota;
      this.mountIp = mountIp;
      this.mountPoint = mountPoint;
      this.storageIp = storageIp;
      this.status = status;
      this.username = username;
      this.password = password;
   }

}