package com.redhat.demo.nas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuthRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AuthRequest() {
    }

}