package com.redhat.demo.nas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuthRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "\u5E33\u865F")
   private java.lang.String username;
   @org.kie.api.definition.type.Label(value = "\u5BC6\u78BC")
   private java.lang.String password;
   @org.kie.api.definition.type.Label(value = "\u8A8D\u8B49\u985E\u5225")
   private java.lang.String authCategory;
   @org.kie.api.definition.type.Label(value = "\u53CD\u994B\u4EE3\u865F")
   private java.lang.String code;
   @org.kie.api.definition.type.Label(value = "Token")
   private java.lang.String accessToken;

   public AuthRequest()
   {
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public java.lang.String getAuthCategory()
   {
      return this.authCategory;
   }

   public void setAuthCategory(java.lang.String authCategory)
   {
      this.authCategory = authCategory;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getAccessToken()
   {
      return this.accessToken;
   }

   public void setAccessToken(java.lang.String accessToken)
   {
      this.accessToken = accessToken;
   }

   public AuthRequest(java.lang.String username, java.lang.String password,
         java.lang.String authCategory, java.lang.String code,
         java.lang.String accessToken)
   {
      this.username = username;
      this.password = password;
      this.authCategory = authCategory;
      this.code = code;
      this.accessToken = accessToken;
   }

}